# Generated by Django 4.1 on 2022-08-25 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comments_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
