# Generated by Django 4.1 on 2022-08-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comments_email_remove_comments_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_urls',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
